version: '2'

services:
  product-service:
    build: ./python
    image: camptocamp/python_app:latest
    ports:
      - 5555:80
  website:
    build: ./website
    image: camptocamp/php_app:latest
    ports:
      - 5556:80
    depends_on:
      - product-service
