version: '2'

services:
  product-service:
    build: ./python
    image: camptocamp/python_app:latest
    ports:
      - XXXX:XX
  website:
    build: ./website
    image: camptocamp/php_app:latest
    ports:
      - XXXXX:XX
    depends_on:
      - XXXXXXXXXXXXXXXXX
